#!/bin/sh

source "$(git --exec-path)/git-sh-setup"

USAGE="\n
git clean-branch            display already gone branches
git clean-branch --delete   delete all branches marked as gone"

Red='\033[0;31m'
Green='\033[0;32m'
Blue='\033[0;34m'
NC='\033[0m' # No Color

if [ $# == 0 ] || [ $# == 1 ]
then
  echo "${Blue}Fetching latest remote branch info${NC}"
  git fetch -p
  Gone_Branchs=$(git branch -vv | grep ': gone]')
  if [ "$1" == '--delete' ]
  then
    echo "${Red}Deleting branches${NC}"
    # $Gone_Branchs | awk '{print $1}' | xargs git branch -D
    echo "${Blue}Done!${NC}"
  else
    if [ "$Gone_Branchs" == '' ]
    then
      echo "${Blue}No gone branches :)${NC}"
    else
      echo "${Red}The following branchs are not tracked by remote${NC}"
      $Gone_Branchs
      echo "${Blue}Use${NC} ${Green}git clean-branch --delete${NC} ${Blue}to delete the untracked branches${NC}"
    fi
  fi
else
  usage
fi
